<a href="https://colab.research.google.com/github/ReynaldoAVZ/Scientific-Machine-Learning-7750/blob/main/HW1/HW1_AppliedMathForMachineLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Consider the two matrices given as:
# A = [1, 4, -3; 2, 5, 4] and B = [4, 1; 2, 6; 0, 3]
---
a) What is the rank of each matrix?

b) Calculate the multiplication AB and BA by hand. Are they equal?

c) What is the rank of AB and BA? In the case of the matrix that becomes
3*3 rank might not be obvious and you can use Python or Matlab to get
the rank (search for the command).

d) One of the two multiplications above were not full rank. Demonstrate that
the matrix is not full rank with another metric beyond rank (you can use
Matlab/Python to calculate that metric).


In [1]:
# import libraries
import numpy as np

# (a) what is the rank of each matrix?

# declare given matrices
A = np.array([[1, 4, -3], [2, 5, 4]])
B = np.array([[4, 1], [2, 6], [0, 3]])

# calculate the rank and print results
rank_A = np.linalg.matrix_rank(A)
rank_B = np.linalg.matrix_rank(B)
print("Problem 1 (a):\n")
print(f"Rank of A: {rank_A}")
print(f"Rank of B: {rank_B}\n")

# (b) calculate the multiplication AB and BA by hand. Are they equal?
AB = np.matmul(A, B)
BA = np.matmul(B, A)
print("Problem 1 (b):\n")
print(f"Result of Matrix A x Matrix B:")
print(f"AB:\n{AB}")
print(f"Result of Matrix B x Matrix A:")
print(f"BA:\n{BA}\n")
if(np.array_equal(AB, BA)):
    print("AB and BA are equal")
    print(f"Dimensions of AB: {np.shape(AB)}")
    print(f"Dimensions of BA: {np.shape(BA)}\n")
else:
    print(f"AB and BA are not equal")
    print(f"Dimensions of AB: {np.shape(AB)}")
    print(f"Dimensions of BA: {np.shape(BA)}\n")

# (c) What is the rank of AB and BA? In the case of the matrix that becomes
# 3 x 3 rank might not be obvious and you can use Python or Matlab to get the
# rank (search for the command).

# calculate the rank and print result
rank_AB = np.linalg.matrix_rank(AB)
rank_BA = np.linalg.matrix_rank(BA)
print("Problem 1 (c):\n")
print(f"Rank of AB: {rank_AB}")
print(f"Dimensions of AB: {np.shape(AB)}")
print(f"Rank of BA: {rank_BA}")
print(f"Dimensions of BA: {np.shape(BA)}\n")

# (d) One of the two multiplications above were not full rank. Demonstrate that
# the matrix is not full rank with another metric beyond rank (you can use
# Matlab/Python to calculate that metric).

# find the number of eigen values for each matrix (can do this if square) and
# if the number of non-zero eigenvalues equals the dim of matrix, then it is
# full rank.
eigenvalues_AB = np.linalg.eigvals(AB)
eigenvalues_BA = np.linalg.eigvals(BA)
tol = 1e-6
nonzero_eigenvalues_AB = eigenvalues_AB[np.abs(eigenvalues_AB) > tol]
nonzero_eigenvalues_BA = eigenvalues_BA[np.abs(eigenvalues_BA) > tol]
print("Problem 1 (d):\n")
print(f"Eigenvalues of AB: {eigenvalues_AB}")
print(f"Dimensions of AB: {np.shape(AB)}")
print(f"Non-zero Eigenvalues of AB: {nonzero_eigenvalues_AB}")
print(f"Number of Non-zero Eigenvalues of AB: {nonzero_eigenvalues_AB.size}")
print(f"Number of Zero-Value Eigenvalues of AB: {eigenvalues_AB.size - nonzero_eigenvalues_AB.size}")
print(f"Eigenvalues of BA: {eigenvalues_BA}")
print(f"Dimensions of BA: {np.shape(BA)}")
print(f"Non-zero Eigenvalues of BA: {nonzero_eigenvalues_BA}")
print(f"Number of Non-zero Eigenvalues of BA: {nonzero_eigenvalues_BA.size}")
print(f"Number of Zero-Value Eigenvalues of BA: {eigenvalues_BA.size - nonzero_eigenvalues_BA.size}\n")


Problem 1 (a):

Rank of A: 2
Rank of B: 2

Problem 1 (b):

Result of Matrix A x Matrix B:
AB:
[[12 16]
 [18 44]]
Result of Matrix B x Matrix A:
BA:
[[ 6 21 -8]
 [14 38 18]
 [ 6 15 12]]

AB and BA are not equal
Dimensions of AB: (2, 2)
Dimensions of BA: (3, 3)

Problem 1 (c):

Rank of AB: 2
Dimensions of AB: (2, 2)
Rank of BA: 2
Dimensions of BA: (3, 3)

Problem 1 (d):

Eigenvalues of AB: [ 4.67619242 51.32380758]
Dimensions of AB: (2, 2)
Non-zero Eigenvalues of AB: [ 4.67619242 51.32380758]
Number of Non-zero Eigenvalues of AB: 2
Number of Zero-Value Eigenvalues of AB: 0
Eigenvalues of BA: [5.13238076e+01 4.50279750e-16 4.67619242e+00]
Dimensions of BA: (3, 3)
Non-zero Eigenvalues of BA: [51.32380758  4.67619242]
Number of Non-zero Eigenvalues of BA: 2
Number of Zero-Value Eigenvalues of BA: 1



# 2. Prove/Investigate the following statements.
---
a) Given an arbitrary matrix A, show that A^TA is always symmetric (show that it is equal to its transpose).

b) Given an arbitrary matrix C and vector x, we can calculate the sign of x^TCx to predict the sign of the eigenvalues (they are the same). Consider a matrix of the general form A^TA, and plug it into this form (x^TCx), and show that the term becomes always positive. Therefore, we can conclude that A^TA always has positive eigenvalues.  

c) Python/Matlab: Generate an arbitrary 4*4 matrix that is NOT full-rank.  
Now add some noise (e.g., generated using random number sampled from
a Normal distribution with standard deviation equal to 10% of the entry’s
value) to all elements of the matrix. What is the rank now? Comment on
your findings.  

d) Matrix decompositions play a big role in linear algebra. Pick one matrix
decomposition (e.g., eigendecomposition, or Schur decomposition, or QR
decomposition, ..). Search and read a bit about the decomposition online.
Explain it very briefly and mention:  for what kind of input matrix it exists and what are the sizes of each matrix appearing in the decomposition.

In [2]:
# (a) Given an arbitrary matrix A, show that ATA is always symmetric (show that
# it is equal to its transpose).

# (b) b) Given an arbitrary matrix C and vector x, we can calculate the sign of xTCx
# to predict the sign of the eigenvalues (they are the same). Consider a matrix
# of the general form ATA, and plug it into this form (xTCx), and show that
# the term becomes always positive. Therefore, we can conclude that ATA
# always has positive eigenvalues.

# (c) c) Python/Matlab: Generate an arbitrary 4*4 matrix that is NOT full-rank.
# Now add some noise (e.g., generated using random number sampled from
# a Normal distribution with standard deviation equal to 10% of the entry’s
# value) to all elements of the matrix. What is the rank now? Comment on
# your findings.

# declare not full-rank matrix
NonFullRankMatrix = np.array([[1, 2, 3, 4],
                              [5, 6, 7, 8],
                              [9, 10, 11, 12],
                              [13, 14, 15, 16]])
print("Problem 2 (c):\n")
print(f"Non-Full-Rank Matrix:\n{NonFullRankMatrix}")
print(f"Dimensions of Non-Full-Rank Matrix: {np.shape(NonFullRankMatrix)}")
print(f"Rank of Non-Full-Rank Matrix: {np.linalg.matrix_rank(NonFullRankMatrix)}\n")

# add noise to non-full-rank matrix with normal distribution and standard
# deviation equal to 10% of the entry's values
noise = np.random.normal(0, 0.1 * np.abs(NonFullRankMatrix), NonFullRankMatrix.shape)
noisy_matrix = NonFullRankMatrix + noise
print(f"Noise Matrix:\n{noise}")
print(f"Non-Full-Rank Matrix + Noise Matrix:\n{noisy_matrix}")
print(f"Dimensions of Noisy Matrix: {np.shape(noisy_matrix)}")
print(f"Rank of Noisy Matrix: {np.linalg.matrix_rank(noisy_matrix)}\n")
print(
    "Comment:\n"
    "The original matrix is rank-deficient because it has \nexact linear",
    "dependencies (its columns/rows lie in a \nlower-dimensional subspace),",
    "which is equivalent to \nhaving det(A)=0 and at least one singular value",
    "exactly \nequal to zero.\nWhen we add random noise drawn from a ",
    "continuous \ndistribution (Normal) to every entry, those exact\nequalities",
    "are almost surely broken, so det(A+E) becomes \nnonzero and the matrix",
    "becomes full rank (rank 4).\nNumerically, this means the singular values",
    "that were zero\nbecome small but positive; if they exceed NumPy's rank",
    "tolerance\nnp.linalg.matrix_rank reports the matrix as full rank."
)


# (d) Matrix decompositions play a big role in linear algebra. Pick one matrix
# decomposition (e.g., eigendecomposition, or Schur decomposition, or QR
# decomposition, ..). Search and read a bit about the decomposition online.
# Explain it very briefly and mention:  for what kind of input matrix it exists
# and what are the sizes of each matrix appearing in the decomposition.

Problem 2 (c):

Non-Full-Rank Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Dimensions of Non-Full-Rank Matrix: (4, 4)
Rank of Non-Full-Rank Matrix: 2

Noise Matrix:
[[ 0.20700634 -0.02919439 -0.2369872  -0.17022255]
 [-0.20414401 -0.6223629  -0.41081047 -0.98471655]
 [ 0.51655119  0.60665736  1.71180918 -1.08529096]
 [ 2.86145762 -0.21173513 -0.533376   -0.51810541]]
Non-Full-Rank Matrix + Noise Matrix:
[[ 1.20700634  1.97080561  2.7630128   3.82977745]
 [ 4.79585599  5.3776371   6.58918953  7.01528345]
 [ 9.51655119 10.60665736 12.71180918 10.91470904]
 [15.86145762 13.78826487 14.466624   15.48189459]]
Dimensions of Noisy Matrix: (4, 4)
Rank of Noisy Matrix: 4

Comment:
The original matrix is rank-deficient because it has 
exact linear dependencies (its columns/rows lie in a 
lower-dimensional subspace), which is equivalent to 
having det(A)=0 and at least one singular value exactly 
equal to zero.
When we add random noise drawn from a  continuous 
distributio